require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'debug.rb'

# Allow top level `include` in some cases
Style/MixinUsage:
  Exclude:
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'benchmark/benchmark.rb'

# Allow longer examples
RSpec/ExampleLength:
  Max: 10
